FROM ruby:3.3

RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

WORKDIR /rails

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]